version: '3'

services:

  platform_outgoing_api:
    build:
        context: ./platform_out/
        dockerfile: Dockerfile.prod
    entrypoint: ['/project/entrypoint.sh']
    command: gunicorn --bind 0.0.0.0:5000 --log-level=debug manage:app
    expose:
      - 5000
    env_file:
      - config.env

  nginx:
    build: ./nginx
    ports:
      - 1338:80
    depends_on:
      - platform_outgoing_api


